name: TechMarket Main Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ejecutar-pruebas:
    uses: ./.github/workflows/templates/template_test.yml
    with:
      node_version: '20'

  construir-y-subir:
    needs: ejecutar-pruebas
    uses: ./.github/workflows/templates/template_build.yml
    with:
      aws_region: 'us-east-1'
      ecr_repository: 'techmarket-backend'
      image_tag: ${{ github.sha }}
    secrets: inherit

  desplegar-en-eks:
    needs: construir-y-subir
    uses: ./.github/workflows/templates/template_deploy.yml
    with:
      # CORRECCIÓN: Usamos la URL completa del ECR que vimos en tus logs
      image_uri: 219241426160.dkr.ecr.us-east-1.amazonaws.com/techmarket-backend:${{ github.sha }}
      cluster_name: 'techmarket-cluster'
      aws_region: 'us-east-1'
      namespace: 'default'
    secrets: inherit
