name: "Template - Deploy EKS (v1.0.0)"
description: "Despliega la imagen en un clúster EKS de AWS"

on:
  workflow_call:
    inputs:
      image_uri:
        required: true
        type: string
      namespace:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar Credenciales AWS
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.aws_region }}

      - name: Actualizar Kubeconfig para EKS
        run: aws eks update-kubeconfig --name ${{ inputs.cluster_name }} --region ${{ inputs.aws_region }}

      - name: Ejecutar despliegue
        run: |
          # 1. Creamos o actualizamos la estructura
          kubectl apply -f deployment.yaml -n ${{ inputs.namespace }}
          
          
          sleep 100
          
          # 3. Actualizamos a la imagen específica del commit
          kubectl set image deployment/techmarket-app myapp=${{ inputs.image_uri }} -n ${{ inputs.namespace }}
          
          # 4. (Opcional) Verificamos que el despliegue sea exitoso
          kubectl rollout status deployment/techmarket-app -n ${{ inputs.namespace }}
